[package]
name = "paramacode/linkage"
version = "0.0.2"
authors = ["parama"]
license = "MIT"
description = "Binary serialization and typed networking for Roblox, built for efficiency and low overhead."
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
